### ISSUE TITLE
Trying to use with koa

### ISSUE THREAD

**Issue by gx0r** [novacrazy/bluebird-co#1]
I put the following in node_modules/koa/lib/application.js 

```
var co = require('co');

const Promise = require('bluebird');
Promise.longStackTraces();
require('bluebird-co')
co.wrap = function(fn) {
    return Promise.coroutine(fn);
}
```

is this the proper approach?

**Comment by novacrazy** [comment]
Basically, you have to make sure every one of your dependencies is requiring the same instance of Bluebird, and then you can just require `bluebird-co` from a script before you use it. You don't need to edit any module files directly, ever.

The easiest way to do that is by making sure your application has bluebird (and co in this case) in its dependencies before you install anything else.

So you'd create your package.json via running `npm init` in your project directory or manually creating it, then run `npm install bluebird co bluebird-co --save`.

Then run `npm install koa koa-router anything-else-koa-related --save`, and so forth. Now when those install, they will use the pre-existing copy of bluebird and co that you installed manually.

Then create a file `index.js` that looks something like:

``` javascript
var Promise = require('bluebird');
var co = require('co');

//Optionally enable long stack traces for debugging
Promise.longStackTraces();

require('bluebird-co');

co.wrap = function(fn) {
    return Promise.coroutine(fn);
}

//Optionally use bluebird Promises globally
global.Promise = Promise;

require('./app.js'); //start your application
```

You should never have to manually edit other libraries code.

However, if you have already populated your package.json with many libraries, you can achieve the desired dependency state by running `npm install bluebird co bluebird-co --save` to save them to your package.json, then `rm -rf ./node_modules` to delete all your dependencies, and finally run `npm install` and it will reinstall all your modules, using the same copy of Bluebird and co for every dependency.

**Comment by gx0r** [comment]
Ah! That makes sense, got it working now. Thanks!

**Comment by novacrazy** [comment]
It's just one of the quirks of NPM and node_modules. If you're not careful you can end up with many copies of the same library being used around your application.

**Comment by novacrazy** [comment]
I'm actually going to reopen this issue in case anyone else has trouble integrating bluebird-co into their stack. It's a subtle problem that I can't really fix, but getting it right really pays off.

**Comment by novacrazy** [comment]
This thread isn't as applicable now that I've switched to using Bluebird as a peer dependency and koa has/is moved/moving away from generators, so I'm going to close it.
