### ISSUE TITLE
Release new version with bluebird 3 support ?

### ISSUE THREAD

**Issue by asafyish** [novacrazy/bluebird-co#2]
Hi,

I see there is already a version working with bluebird 3, but it's on npm... can we haz new version ?

Thanks !

**Comment by novacrazy** [comment]
Yeah, I was really hoping I could get my tests working with Babel 6 before releasing a new version, but the Babel team doesn't seem to care about their async-to-method transformer at all, which is still completely broken.

I'll see what I can do to ensure everything is correct, though, and publish a new version in the next day or so.

**Comment by asafyish** [comment]
Thanks !

**Comment by novacrazy** [comment]
Bluebird `^3.x` added as a peer dependency in version 2.0.0
