### ISSUE TITLE
Add .wrap method

### ISSUE THREAD

**Issue by bisubus** [novacrazy/bluebird-co#3]
Do you consider adding `.wrap` method and expose API similar to that one of `co`?

This way the library could be a drop-in replacement for `co`.

**Comment by novacrazy** [comment]
Sure. Any suggestions for other aliases?

**Comment by bisubus** [comment]
No, that is all. `co` function which has `co.wrap` property is fine. `co` also has `co.co` alias but it seems that it affects nothing.

I've mocked `co` with this module

```
let Bluebird = require('bluebird');
let bluebirdCo = require('bluebird-co/manual');

Bluebird.coroutine.addYieldHandler(bluebirdCo.toPromise);

function co(fn, ...args) {
    return Bluebird.coroutine(fn).apply(this, args);
}

co.wrap = Bluebird.coroutine;

module.exports = co;
```

and run through `co` specs, it passes 3/4.

It would be great to have something like `var co = require('bluebird-co').co` instead;

**Comment by novacrazy** [comment]
[`.wrap`](https://github.com/novacrazy/bluebird-co#coroutinegfn-generatorfunction---function) added in 2.0.0

[`.co`](https://github.com/novacrazy/bluebird-co#executegfn-generatorfunction-args--any---promiseany) added in 2.1.0

**Comment by puzrin** [comment]
@novacrazy `co` exports function itself, https://github.com/tj/co/blob/4.6.0/index.js#L12 . Could you add it? I like to use:

``` js
co = require('co');

co(...)
co.wrap(...)
```

It would be nice if `bluebird-co` will be 100% transparent for such pattern.

**Comment by novacrazy** [comment]
Since I chose ES6 to write this in, it's not really the best practice to export a function as the default value. Plus I kind of want it to be distinct from co in this way. If you really want to use it like that, do this:

``` javascript
import {co, wrap} from 'bluebird-co'; //or var co = require('bluebird-co').co;

co(...);
wrap(...);
```

Although I need to do a bit of cleanup, so I can probably add `co.wrap` instead of just `wrap`, so it would be like this:

``` javascript
import {co} from 'bluebird-co';

co(...);
co.wrap(...);
```

**Comment by puzrin** [comment]
Having .co + .co.wrap is nice idea.

My preference is `co` on client (small size) and `bluebird-co` on server (speed). It's convenient when replacement can be done with single line.
